// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Mr28C8JZQatxYQAM9a3esTBZiSUcUUI',
    appId: '1:825941701407:web:53c95486893adedb97f62a',
    messagingSenderId: '825941701407',
    projectId: 'smart-niti-e2de6',
    authDomain: 'smart-niti-e2de6.firebaseapp.com',
    storageBucket: 'smart-niti-e2de6.firebasestorage.app',
    measurementId: 'G-SYQ4EMSNQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4AUtO4SF00ORMHLycvXZMUYC-8h1OTFI',
    appId: '1:825941701407:android:efecd35d259bdd5e97f62a',
    messagingSenderId: '825941701407',
    projectId: 'smart-niti-e2de6',
    storageBucket: 'smart-niti-e2de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEg5gPSLSArpUwzWSdRe7Zf5IkLsYxk7k',
    appId: '1:825941701407:ios:0ef9d1da60fc4ce797f62a',
    messagingSenderId: '825941701407',
    projectId: 'smart-niti-e2de6',
    storageBucket: 'smart-niti-e2de6.firebasestorage.app',
    androidClientId: '825941701407-q4s19akccdv9qda9l0p5bldumloqcjud.apps.googleusercontent.com',
    iosClientId: '825941701407-hqmbfol97ecp98qifjeqbk8tff5b91rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.juristicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEg5gPSLSArpUwzWSdRe7Zf5IkLsYxk7k',
    appId: '1:825941701407:ios:0ef9d1da60fc4ce797f62a',
    messagingSenderId: '825941701407',
    projectId: 'smart-niti-e2de6',
    storageBucket: 'smart-niti-e2de6.firebasestorage.app',
    androidClientId: '825941701407-q4s19akccdv9qda9l0p5bldumloqcjud.apps.googleusercontent.com',
    iosClientId: '825941701407-hqmbfol97ecp98qifjeqbk8tff5b91rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.juristicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Mr28C8JZQatxYQAM9a3esTBZiSUcUUI',
    appId: '1:825941701407:web:9586d93e77c25eb097f62a',
    messagingSenderId: '825941701407',
    projectId: 'smart-niti-e2de6',
    authDomain: 'smart-niti-e2de6.firebaseapp.com',
    storageBucket: 'smart-niti-e2de6.firebasestorage.app',
    measurementId: 'G-MNQXGZLVMS',
  );
}
