version: '3.8'

services:
  backend:
    build:
      context: ./smart_niti_app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./smart_niti_app/backend/app:/backend/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    restart: always
    networks:
      - smartniti_net

networks:
  smartniti_net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.16.238.0/24
        - subnet: fd00:1::/64