version: '3.8'

services:
  backend:
    build:
      context: ./smart_niti_app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./smart_niti_app/backend/app:/backend/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    restart: always
